apiVersion: v1
kind: Service
metadata:
  name: {{ template "spring-boot-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "spring-boot-app.name" . }}
    helm.sh/chart: {{ include "spring-boot-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ template "spring-boot-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
